spring:
  datasource:
    druid:
      max-open-prepared-statements: 80 # 最大预处理语句
      max-active: 8 # 最大连接数量
      initial-size: 8 # 初始连接数量
      min-idle: 8 # 最小空闲数量
  redis:
    database: 0 # 数据库序号
    host: 127.0.0.1 # 连接主机
    port: 6379 # 端口号
    password: # Redis密码
  mvc:
    static-path-pattern: /** # 静态资源映射路径
  resources:
    add-mappings: true # 为资源文件建立映射
    static-locations: file:${framework.upload.fs.path} # 静态资源位置
  rabbitmq:
    host: localhost
    port: 41906
    username: guest
    password: guest
  cloud:
    circuit:
      breaker:
        enabled: false # 关闭熔断

eureka: # 注册中心配置
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/ # 注册地址
    healthcheck:
      enabled: true # 开启健康检查
    registry-fetch-interval-seconds: 60 # 5秒拉取信息
  instance:
    lease-renewal-interval-in-seconds: 2 # Eureka客户端向服务端发送心跳的时间间隔，单位为秒（客户端告诉服务端自己会按照该规则），默认30
    lease-expiration-duration-in-seconds: 180 # Eureka服务端在收到最后一次心跳之后等待的时间上限，单位为秒，超过则剔除（客户端告诉服务端按照此规则等待自己），默认90

framework: # 自定义配置
  field-dict-translator-enabled: true # 开启数据字典解析钩子
  common-info-cache-enabled: true # 开始公用数据缓存
  database: # 数据库配置
    # driver-class-name: com.mysql.cj.jdbc.Driver # 数据库驱动
    # jdbc-url-type: jdbc # jdbc url类型
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver # 数据库驱动
    jdbc-url-type: jdbc:p6spy # jdbc url类型
    host: localhost # 数据库主机
    port: 3306 # 数据库端口
    name: spring-cloud-framework-new # 数据库名称
    username: root # 用户名
    password: 199294 # 密码
  wx:
    cp: # 企业微信配置
      corp-id: ww9a6f23d2f63dce82 # 企业ID
      corp-secret: qZN9rK-6IiPNkRhgEByLs8k0mRSSzRZx56IQ6mZIQHI # 企业密匙
      org: # 机构端小程序
        agent-id: 1000005 # 代理ID
        secret: SsyXb7VG2_Cvs3BBU_5SqBOX20JzaOjY0PWZxp4bWW4 # 管理密匙
    mini-app: # 小程序配置
      org: # 机构端小程序
        app-id: wx1ca74a24d1b1b094 # appId
        app-secret: 32bdf791d33bb488d60522026c838cb5 # appSecret
    mp: #公众号
      configs:
        - appid: wx94b9f159ba6348d6 #微信公众号或者小程序等的appid 必填
          secret: 150bd05b114adb7685edd5409a5c91f2 #微信公众号或者小程序等的secret 必填
          token: zhixingruijing
          aesKey: R1KsbX9ZMcQJYJWnQEvg5ybkm2Qy3lgUfUUYFMhQ16m
          msgDataFormat: JSON
  upload: # 文件上传配置
    fs: # 本地文件上传配置
      path: /Users/yangchangliang/Temp/Upload # 文件上传路径
      domain: http://localhost:8100/system # 文件访问域名
      max-size: 5242880 # 5兆大小
  beans: # Bean装配配置
    composite-wx-ma-service: true # 装配微信小程序配置
  message:
    mapping-store-type: yml
  tencent: # 腾讯云服务配置
    app-id: 1257263570
    secret-id: AKID2oLFrNQhSxDuObLKCn6fz2pNg8MJBt63
    secret-key: FOUWK1ShiYs67yg8Mn042oMehU2QejeJ
