server:
  port: 8000 # 端口号

spring:
  application:
    name: eureka # 应用名称
  profiles:
    active: dev # 激活的配置文件

eureka:
  instance:
    prefer-ip-address: true # 使用IP
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port} # 实例名

management:
  endpoints:
    web:
      exposure:
        include: "*"
